name: "hello_world"

on:
  push:
    branches:
      - master
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest 
    steps: 
      - name: "print hello world"
        run: echo "Hello world"

      - name: "print current date"
        run: date